### PR TITLE
added babies and lions in costco

### PR DESCRIPTION
**Pull request by SeanLuo-FSWD**
Hey Hailey, 

This is supposed to solve issue #1 , does that work?

Sean

### CODE REVIEW

**Comment by hihailey** [comment]
Hi, Sean.
New items don't fit Costo as well! We can not buy babies with money. Also, lions can be dangerous for people. Please fix it again.

**Comment by SeanLuo-FSWD** [comment]
Hey @hihailey , 

I was gonna make a dark joke involving babies and lions but I don't want to be fired....maybe another time ;)

Does this work now? This commit resolves issue #1 .

**Review by hihailey — CHANGES_REQUESTED** [review]
I need more items. Please add more and more!

**Comment by SeanLuo-FSWD** [comment]
Okay boss, more items added. 

Can you believe they sell TVs and jewelry at Costco? I mean, what is more sad and depressing than buying your jewelry at Costco?

**Comment by hihailey** [comment]
Great job Sean! You are not fired. You can buy jewelry at the holt renfrew.

**Pull request merged**
